# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f24fe657aaaf7b2a8053f63228b03eddfeb2a255afbc1de0eeb6182ae6dfe2f4cd59116502903940e880c47f58c56b5336b2dff7ede47e9da8fea5518b27549e

test:
  secret_key_base: fb2df2e36948481882694eba76f45506676ab787f4a38f2a1ad81dadd49150141c6b095df4e864c74b30188bb135097830269e730732e0c97b58f1e49397eab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
